-- Classroom sessions accept one final submission per student.
-- Fail atomically on historical duplicates; never discard student work silently.
ALTER TABLE public.session_submissions
  ADD CONSTRAINT session_submissions_session_user_key UNIQUE (session_id, user_id);

-- Quick sessions have a different ID namespace and keep the best result.
-- Do not infer ownership of historical rows from coincident numeric IDs.
-- Audit on 2026-09-18 confirmed both source submission/session tables were empty.
CREATE TABLE public.lesson_session_submissions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id integer NOT NULL REFERENCES public.lesson_sessions(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  code text NOT NULL,
  score numeric(8,2) NOT NULL DEFAULT 0,
  is_correct boolean NOT NULL DEFAULT false,
  execution_time integer,
  submitted_at timestamp NOT NULL DEFAULT now(),
  CONSTRAINT lesson_session_submissions_session_user_key UNIQUE (session_id, user_id)
);
CREATE INDEX idx_lesson_session_submissions_user ON public.lesson_session_submissions(user_id);
ALTER TABLE public.lesson_session_submissions ENABLE ROW LEVEL SECURITY;
